name: Run Spectral on Pull Requests

on:
  - push
  - pull_request

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Run Spectral
      - uses: roesekoSICKAG/spectral-action@master
        with:
          file_glob: "JSON_for_IO-Link.yaml"
          spectral_ruleset: .spectral.yaml