name: Run Spectral on Pull Requests

on:
  - push
  - pull_request

jobs:
  build:
    name: Run Spectral
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v3

      # Run Spectral
      - uses: stoplightio/spectral-action@v0.8.12
        with:
          file_glob: "JSON_for_IO-Link_unmerged.yaml"
          spectral_ruleset: .spectral.yaml

      # Run Spectral
      - uses: stoplightio/spectral-action@v0.8.12
        with:
          file_glob: "MQTT_for_IO-Link_unmerged.yaml"
          spectral_ruleset: .spectral.yaml
