name: CI Pipeline

on:
  - push
  - pull_request

jobs:
  merge:
    name: Run swagger-merger API specifications
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # install swagger-merger
      - name: install swagger-merger
        run: npm install -g swagger-merger

      # Run swagger-merger
      - name: Run swagger-merger
        run: |
          swagger-merger -i MQTT_for_IO-Link.yaml schemas.yaml examples.yaml -o MQTT_for_IO-Link_merged.yaml
          swagger-merger -i JSON_for_IO-Link.yaml schemas.yaml examples.yaml -o JSON_for_IO-Link_merged.yaml
      
      - name: Run Spectral on Async API Spec        
        uses: stoplightio/spectral-action@v0.8.11
        # Run Spectral
        with:
          file_glob: "MQTT_for_IO-Link_merged.yaml"
          spectral_ruleset: .spectral.yaml
      
      - name: Upload merged MQTT_for_IO-Link YAML file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mqtt-yaml
          path: MQTT_for_IO-Link_merged.yaml

      - name: Run Spectral on OpenAPI Spec
        uses: stoplightio/spectral-action@v0.8.11
        # Run Spectral
        with:
          file_glob: "JSON_for_IO-Link_merged.yaml"
          spectral_ruleset: .spectral.yaml
          
      - name: Upload merged JSON_for_IO-Link YAML file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: json-yaml
          path: JSON_for_IO-Link_merged.yaml
